Don't enable New Relic in local development
`NEW_RELIC_LICENSE_KEY` was picking up `aaa` value
from our `unocha/nodejs` Docker container parent image.
That means that New Relic is loaded locally, so we get
an error:
```
New Relic for Node.js halted startup due to an error:
Error: Failed to connect to collector
```
which is masked by `Unsupported use of console.error(),
please use a LogContext instead`

Avoid loading New Relic locally by setting empty value
for `NEW_RELIC_LICENSE_KEY` env variable.